M48
; DRILL file KiCad 10.0.3 date 2026-07-04T14:53:49
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-04T14:53:49+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X156.7Y-70.58
X159.24Y-70.58
T2
X152.4Y-71.49
X152.4Y-89.55
X167.136Y-71.484
X167.136Y-89.55
M30
